apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: Checkout and register too
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - rthomas-test
      - main
jobs:
  checkout:
    steps:
      - name: Register artifact version - commit supplied
        uses: cloudbees-io/register-build-artifact@CBP-15158-2
        with:
          name: rtFactRegisterFresh
          version: 1.0.1
          url: docker.io/myapp1/myimg:1.0.1
          digest: sha256:5e0687d9471728b0a200e0a3840fa16466150c58f628dc6e6c40a9b07e3b360x
          commit: a
          commit-url: b
          ref: c
          repository-url: d
      - name: Register artifact version - no commit info
        uses: cloudbees-io/register-build-artifact@CBP-15158-2
        with:
          name: rtFactRegisterFresh2
          version: 1.0.1
          url: docker.io/myapp1/myimg:1.0.1
          digest: sha256:5e0687d9471728b0a200e0a3840fa16466150c58f628dc6e6c40a9b07e3b360y
